/** @type {import('tailwindcss').Config} */
// Tokens mirror src/design-system/tokens/*.css — utilities point at the CSS
// variables so live theme edits in those files flow through Tailwind classes.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        swamp: {
          950: 'var(--swamp-950)',
          900: 'var(--swamp-900)',
          800: 'var(--swamp-800)',
          700: 'var(--swamp-700)',
          600: 'var(--swamp-600)',
          500: 'var(--swamp-500)',
          400: 'var(--swamp-400)',
          300: 'var(--swamp-300)',
          DEFAULT: 'var(--swamp-700)',
        },
        cream: {
          50: 'var(--cream-50)',
          100: 'var(--cream-100)',
          200: 'var(--cream-200)',
          300: 'var(--cream-300)',
          400: 'var(--cream-400)',
          500: 'var(--cream-500)',
          DEFAULT: 'var(--cream-200)',
        },
        ink: {
          950: 'var(--ink-950)',
          900: 'var(--ink-900)',
          800: 'var(--ink-800)',
          700: 'var(--ink-700)',
          DEFAULT: 'var(--ink-900)',
        },
        mustard: {
          DEFAULT: 'var(--mustard)',
          deep: 'var(--mustard-deep)',
          soft: 'var(--mustard-soft)',
        },
        terracotta: {
          DEFAULT: 'var(--terracotta)',
          deep: 'var(--terracotta-deep)',
          soft: 'var(--terracotta-soft)',
        },
        teal: {
          DEFAULT: 'var(--teal)',
          deep: 'var(--teal-deep)',
          soft: 'var(--teal-soft)',
        },
        olive: {
          DEFAULT: 'var(--olive)',
          deep: 'var(--olive-deep)',
        },
        plum: 'var(--plum)',
        'clay-pink': 'var(--clay-pink)',
        // Semantic aliases
        'surface-bg': 'var(--surface-bg)',
        'surface-bg-deep': 'var(--surface-bg-deep)',
        'surface-raised': 'var(--surface-raised)',
        'surface-card': 'var(--surface-card)',
        'surface-card-alt': 'var(--surface-card-alt)',
        'text-on-dark': 'var(--text-on-dark)',
        'text-on-dark-muted': 'var(--text-on-dark-muted)',
        'text-on-dark-faint': 'var(--text-on-dark-faint)',
        'text-on-light': 'var(--text-on-light)',
        'text-on-light-muted': 'var(--text-on-light-muted)',
        'border-ink': 'var(--border-ink)',
        'border-hair': 'var(--border-hair)',
        'border-cream': 'var(--border-cream)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        body: 'var(--font-body)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        'display-xl': 'var(--fs-display-xl)',
        'display-lg': 'var(--fs-display-lg)',
        'display-md': 'var(--fs-display-md)',
        'display-sm': 'var(--fs-display-sm)',
        h1: 'var(--fs-h1)',
        h2: 'var(--fs-h2)',
        h3: 'var(--fs-h3)',
        lg: 'var(--fs-lg)',
        base: 'var(--fs-base)',
        sm: 'var(--fs-sm)',
        xs: 'var(--fs-xs)',
        '2xs': 'var(--fs-2xs)',
      },
      letterSpacing: {
        display: 'var(--ls-display)',
        label: 'var(--ls-label)',
        wide: 'var(--ls-wide)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        pill: 'var(--radius-pill)',
      },
      borderWidth: {
        thin: 'var(--border-thin)',
        DEFAULT: 'var(--border)',
        thick: 'var(--border-thick)',
        chunky: 'var(--border-chunky)',
      },
      boxShadow: {
        'sticker-xs': 'var(--shadow-sticker-xs)',
        'sticker-sm': 'var(--shadow-sticker-sm)',
        sticker: 'var(--shadow-sticker)',
        'sticker-lg': 'var(--shadow-sticker-lg)',
        'sticker-press': 'var(--shadow-sticker-press)',
        'soft-sm': 'var(--shadow-soft-sm)',
        soft: 'var(--shadow-soft)',
        'soft-lg': 'var(--shadow-soft-lg)',
        inset: 'var(--shadow-inset)',
        focus: 'var(--glow-focus)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
      },
      maxWidth: {
        'container-sm': 'var(--container-sm)',
        'container-md': 'var(--container-md)',
        'container-lg': 'var(--container-lg)',
      },
      transitionTimingFunction: {
        squish: 'var(--ease-squish)',
        bloom: 'var(--ease-bloom)',
        drip: 'var(--ease-drip)',
      },
      transitionDuration: {
        instant: '90ms',
        fast: '150ms',
        DEFAULT: '240ms',
        slow: '420ms',
        bloom: '640ms',
      },
    },
  },
  plugins: [],
};
